### Create a new report

POST http://localhost:3000/reports/create
Content-Type: application/json

{
    "make": "Ford",
    "model": "Mustang",
    "year": 2012,
    "price": 23000,
    "mileage": 10000,
    "lat": 10.0000,
    "lng": -10.0000
    
}


### Change Report Approval Status
PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
    "approved": true
}


### Get a new estimate on an existing vehicle

GET http://localhost:3000/reports?make=Ford&model=Mustang&year=2012&mileage=10000&lat=10.0000&lng=-10.0000