### Create a new report

POST https://peaceful-chamber-98453-c8b3feb3fc78.herokuapp.com/products/create
Content-Type: application/json

{
    "barcode": "8692674301761",
    "name" : "Tombow Ultra Polymer 0.7 2B 12pc",
    "warehouse": 3,
    "isle"  : 2,
    "rack" : 3
}


### Change Report Approval Status
PATCH https://peaceful-chamber-98453-c8b3feb3fc78.herokuapp.com/products/8692674301761
Content-Type: application/json

{
    "isle": 7
}

### Upload a new image to an existing product
POST https://peaceful-chamber-98453-c8b3feb3fc78.herokuapp.com/products/8692674301761/image
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="product_image.jpeg"
Content-Type: image/jpeg

< ./togg.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get a new estimate on an existing vehicle

GET https://peaceful-chamber-98453-c8b3feb3fc78.herokuapp.com/products/8692674301761